### ISSUE TITLE
libart.so, libsigchain.so ARM version for x86?

### ISSUE THREAD

**Issue by sorgelig** [rovo89/android_art#12]
In Zenfone 2 ROM, i see /system/lib/arm dir, and there are ARM versions of libart.so, libsigchain.so.
In what cases these libs are used? Do we need to compile xposed ARM version of mentioned libraries?

**Comment by rovo89** [comment]
Not sure what these files are used for. I wonder if these libs could be used by an x86 processor at all. Did you notice any issues which could be caused by not replacing these files?

**Comment by sorgelig** [comment]
I didn't notice any specific to these libraries issues till i discovered their presence there.
May be they automatically put there because some other ARM library dependencies. /system/lib/arm used for arm-only applications as i guess. But since ARM code should be handled by libhoudini on x86, i don't know why all those ARM libraries are present originally. 
I've just compiled ARM version and put there. Just in case. Because I don't know their task as well, i've decided to ask you :)
