### ISSUE TITLE
Redmi Note 2

### ISSUE THREAD

**Issue by avenantsoftware** [rovo89/android_art#18]
xposed used to work on Redmi Note 2 till MIUI 5.9.18, afterwards not anymore => bootloop, on most other xiaomi devices with MIUI 7 xposed works.

**Comment by rovo89** [comment]
Please post a logcat of the bootloop, otherwise I can't help you.

**Comment by wanam** [comment]
@rovo89 Can this be related to https://android.googlesource.com/platform/frameworks/base.git/+/d4d3181d013f8d9b96de8e396b029f8a418894a7%5E!/#F0 being ported to Kitkat? a similar issue was reported here: http://forum.xda-developers.com/xposed/error-xposed-upgrading-rom-miui-v7-t3243368

I suspect this because i saw somewhere some people posting a patch "fix" that contains "libandroid_runtime.so", so i guess the only thing this fix do is to put back the old implementation of "AndroidRuntime::start()".

By the way same thing was done on the newest TouchWiz Roms running Android 5.0.

@spambus Can you upload your stock "/system/lib/libandroid_runtime.so"?

**Comment by avenantsoftware** [comment]
http://avenant.net/libandroid_runtime.so  => from MIUI 5.10.22

**Comment by wanam** [comment]
I can confirm they patched it with the above commit.
New one with "zygote" parameter:
AndroidRuntime::start(char const*, android::Vectorandroid::String8 const&, bool)
Mangled name:
_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb

Old one (from the fix patch):
android::AndroidRuntime::start(android::AndroidRuntime *__hidden this, const char *, const char *)
And it's mangled name:
_ZN7android14AndroidRuntime5startEPKcS2_

**Comment by avenantsoftware** [comment]
@ wanam what does this mean?

**Comment by wanam** [comment]
@spambus It means this xposed patch: https://github.com/rovo89/Xposed/commit/d0551ccb86f27e7bc34953bc16d4ca9754be560b should to be applied for KK (https://github.com/rovo89/Xposed/blob/master/app_main.cpp#L258) as well.

**Comment by rovo89** [comment]
Is MIUI 5.10.22 really Kitkat? If so, you will probably have to wait a few months until I'm ready to publish updates for pre-Lollipop again. I have changed very many things for Lollipop, e.g. I moved the runtime-specific code to libraries. This is also briefly tested for Dalvik, but needs much more testing. I will then also need to completely rewrite the installation routines to handle this etc.

If it's Lollipop /  Android 5.0, then there's a bigger chance that this will be fixed some time soon, I'll backport some changes I did for Marshmallow to the Lollipop releases.

@wanam: The two variants you mentioned look very different, e.g. the new one uses a Vector. Are you sure that both libs are from the same release? I would expect that they just backport the security fix, for which they need the additional boolean parameter.

**Comment by wanam** [comment]
@rovo89 Indeed i noticed the difference, and it's only a guess since i don't own any device running MIUI, but according to some discussions on xda, MIUI 7 is based on LL and KK depending on the device, and this issue related to the KK ones only.

**Comment by avenantsoftware** [comment]
MIUI 5.x.y is the Developer version of MIUI 7 wich is standard rooted, they release weekly updates with bugfixes, MIUI 7 = android 5.0.2, the numbering for the developer version is a little confusing, the 5 in MIUI 5.x.y stands for android 5, and the x is the month and the y is the day of the month when it is released.

currently they are at MIUI 5.11.5, tomorrow there will be a new version MIUI 5.11.12, they release a new version every week every thursday

**Comment by rovo89** [comment]
The issue with recent 5.0 ROMs should be fixed with Xposed version 78.
