### ISSUE TITLE
Xposed doesn't get active

### ISSUE THREAD

**Issue by aminya** [rovo89/android_art#23]
Hi @rovo89 . I have samsung galaxy s2 with cm12.1 offcial & dorimanx-gsstudios build kernel. I flashed the zip. & rebooted but it didnt get actived. I had installed xposed installer app with some modules in it before flash this time. But i have uninstalled the xposed after reflash rom.
This is the log:
12-23 23:11:11.927 I/Xposed  ( 2928): -----------------
12-23 23:11:11.927 I/Xposed  ( 2928): Starting Xposed version 79, compiled for SDK 22
12-23 23:11:11.927 I/Xposed  ( 2928): Device: GT-I9100 (samsung), Android version 5.1.1 (SDK 22)
12-23 23:11:11.927 I/Xposed  ( 2928): ROM: cm_i9100-userdebug 5.1.1 LMY48Y cd69d232f7 test-keys
12-23 23:11:11.927 I/Xposed  ( 2928): Build fingerprint: samsung/GT-I9100/GT-I9100:4.1.2/JZO54K/I9100XWMS2:user/release-keys
12-23 23:11:11.927 I/Xposed  ( 2928): Platform: armeabi-v7a, 32-bit binary, system server: yes
12-23 23:11:11.927 I/Xposed  ( 2928): SELinux enabled: no, enforcing: no
12-23 23:11:14.147 E/Xposed  ( 2928): Found /data/data/de.robv.android.xposed.installer/conf/disabled, not loading Xposed

**Comment by rovo89** [comment]
`Found /data/data/de.robv.android.xposed.installer/conf/disabled, not loading Xposed"`
Delete this file and it should work. I might do this automatically in the installer in the future as many people seem to have created this file (manually or via a 3rd party "disabler" zip) and then forgot about it...
