### ISSUE TITLE
Stuck at Boot after Flash xposed-SDK21-arm64

### ISSUE THREAD

**Issue by privatezs** [rovo89/android_art#24]
[logcat.txt](https://github.com/rovo89/android_art/files/71884/logcat.txt)
i attached the logcat hope you can help
i already flashed uninstaller-arm64
my phone is Lenovo A7000-a
cleared Dalvik Twice and reboot after each time

**Comment by rovo89** [comment]
If you have already flashed the uninstaller, then it can't be Xposed. The log doesn't show anything special either - it stops after 80 seconds though, when the boot isn't finished yet.
