### ISSUE TITLE
Xposed causes crash/reboot on Sony Xperia Z4 Tablet WiFi

### ISSUE THREAD

**Issue by jelbo** [rovo89/android_art#27]
Hello,

I have an issue with Xposed on the Sony Xperia Z4 Tablet WiFi (SGP712, karin_windy), running Android 5.0.2 on an ARM64 Snapdragon 810. The exact Sony firmware is 28.0.A.8.260, R6A. Well, even more exact it is CDA 1295-4711, Germany, Customized DE. ROM is odexed, stock, but running a custom kernel (AndroPlusKernel v10, http://forum.xda-developers.com/z4-tablet/development/kernel-andropluskernel-v1-t3170689, needed for root) and SuperSU.

When I flash Xposed (`xposed-v79-sdk21-arm64.zip`), clear Cache/Dalvik and reboot the device, it will 'optimize' all of my apps, but when that successfully completes, the device crashes and reboots at the lockscreen or moments after getting into the homescreen or an app. It will also crash the second boot, moments after the lockscreen appears.

This is without any Xposed modules activated. As soon as I uninstall Xposed using `xposed-uninstaller-20150831-arm64.zip`, erase cache/Dalvik, the device does not crash and reboot anymore.

I collected some logcats (using `adb logcat -v time > logcat.txt`, as soon as I could @ the 'optimizing apps' screen) in various scenario's.

`SGP712_logcat_normal-boot.txt`
`SGP712_logcat_1st-boot-xposed-v79.txt`
`SGP712_logcat_2nd-boot-xposed-v79.txt`

[logcats.zip](https://github.com/rovo89/android_art/files/87302/logcats.zip)
https://drive.google.com/folderview?id=0B3--EMNkM4LaOWlTN1hEb193R28&usp=sharing

I hope there isn't too much noise in these logs, as I have quite a lot of apps doing stuff.

I also had the issue with the device flashed to stock from scratch, wiped and flashing AndroPlusKernel, TWRP 2.8.7.0 and SuperSU 2.46.

**Comment by jelbo** [comment]
Some things that I found strange/worrying:

`01-12 13:56:32.031 E/dex2oat ( 1719): Failed to open dex from file descriptor for zip file '/system/framework/com.playstation.remoteplayident.jar': Entry not found`
`01-12 13:56:32.439 E/dex2oat ( 1735): Failed to open dex from file descriptor for zip file '/system/framework/SemcGenericUxpRes/SemcGenericUxpRes.apk': Entry not found`
`01-12 13:56:32.769 E/dex2oat ( 1751): Failed to open dex from file descriptor for zip file '/system/framework/com.playstation.remoteplayident.jar': Entry not found`
`01-12 13:56:50.299 E/dex2oat ( 2512): Failed to open dex from file descriptor for zip file '/system/priv-app/SemcAlbum-albumLive-release/SemcAlbum-albumLive-release.apk': Entry not found`

There look like proprietary Sony apps and make me think about the known 'corrupted Sony odex files' issue with Xposed (see https://github.com/rovo89/Xposed/issues/64), though I don't see a `java.lang.ArrayIndexOutOfBoundsException` anywhere.

`01-12 13:57:08.635 F/libc    ( 3667): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1c in tid 3688 (Signal Catcher)`
`01-12 13:57:08.753 I/DEBUG   (  644): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c`
`01-12 13:57:08.917 F/libc    ( 1340): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 1349 (Signal Catcher)`
`01-12 13:57:12.170 I/DEBUG   (  644): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8`

and

`01-12 13:56:59.206 E/ImsSenderRxr( 3485): Exception in socket create'java.io.IOException: No such file or directory`
`01-12 13:56:59.206 I/ImsSenderRxr( 3485): Couldn't find qmux_radio/rild_ims0socket; retrying after timeout`
`01-12 13:57:03.207 E/ImsSenderRxr( 3485): Exception in socket create'java.io.IOException: No such file or directory`
`01-12 13:57:03.207 I/ImsSenderRxr( 3485): Couldn't find qmux_radio/rild_ims0socket; retrying after timeout`
`01-12 13:57:07.208 E/ImsSenderRxr( 3485): Exception in socket create'java.io.IOException: No such file or directory`
`01-12 13:57:07.208 I/ImsSenderRxr( 3485): Couldn't find qmux_radio/rild_ims0socket; retrying after timeout`
`01-12 13:57:11.210 E/ImsSenderRxr( 3485): Exception in socket create'java.io.IOException: No such file or directory`
`01-12 13:57:11.210 I/ImsSenderRxr( 3485): Couldn't find qmux_radio/rild_ims0socket; retrying after timeout`

There's more, but I can't really interpret them anyway.

I suspect it has something to do with the long time fixed 'max open file' issue on Sony ROMs that was discussed in https://github.com/rovo89/Xposed/issues/31, because my `ulimit -n` gives 1024 and the problem that started with random reboots is now so bad the device reboots almost immediately after Android is booted and finished optimizing apps. I think that's because I have lots of apps installed, which might accelerate the crash? When I had just a handful of apps I could use the device for a longer time before crashing. It shouldn't happen, right, because I'm running the latest Xposed (v79).

More info on XDA: http://forum.xda-developers.com/z4-tablet/help/indicate-freeze-black-screen-4x-t3286996

**Comment by jelbo** [comment]
I got a look at the tombstone_00 that was written, and it says `pid: 3667, tid: 3688, name: Signal Catcher  >>> com.google.android.gms <<<`

This looks an awful lot like @dl12345's Xperia issue that got fixed a long time ago (see http://forum.xda-developers.com/xperia-z4/general/identified-cause-xposed-bootloop-z3-t3213307/post63125974#post63125974)

Since this report, I've started freshly and ran the device for some time without Xposed. While having quite a bit of apps installed, I flashed Xposed again and it started to randomly crash (again). I managed to just catch one using continuous logcat logging using CatLog.

The (imo) relevant logcat bits:

`01-28 20:19:10.371 I/Process ( 1734): Sending signal. PID: 32331 SIG: 3`
`01-28 20:19:10.378 I/art     (32331): Thread[9,tid=32344,WaitingInMainSignalCatcherLoop,Thread*=0x7f74637800,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3`
`01-28 20:19:10.484 F/libc    (32331): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 32344 (Signal Catcher)`
`01-28 20:19:10.571 I/Process ( 1734): Sending signal. PID: 1734 SIG: 3`
`01-28 20:19:10.573 I/art     ( 1734): Thread[9,tid=1748,WaitingInMainSignalCatcherLoop,Thread*=0x7f74637800,peer=0x12c02080,"Signal Catcher"]: reacting to signal 3`
[...]
`01-28 20:19:10.656 I/DEBUG   (  652): pid: 32331, tid: 32344, name: Signal Catcher  >>> org.kustom.wallpaper.service <<<`
`01-28 20:19:10.656 I/DEBUG   (  652): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4`
`01-28 20:19:10.726 I/DEBUG   (  652):     x0   0000000000000028  x1   0000000000000004  x2   6c74636f695f5f0e  x3   0000000000000070`
`01-28 20:19:10.727 I/DEBUG   (  652):     x4   0000007f81ed4a00  x5   0000007f81ed4998  x6   0000000000000000  x7   0000000000001002`
`01-28 20:19:10.727 I/DEBUG   (  652):     x8   0000007f81ed4760  x9   0000000000001002  x10  00000000000000b0  x11  0000007f6c930c07`
`01-28 20:19:10.727 I/DEBUG   (  652):     x12  0000000000000020  x13  29d54f8f157c1948  x14  29d54f8f157c1948  x15  0000007f81ed41dc`
`01-28 20:19:10.727 I/DEBUG   (  652):     x16  0000007f82e2bfd8  x17  0000007f82a7fac8  x18  0000000000000028  x19  0000007f81ed4760`
`01-28 20:19:10.727 I/DEBUG   (  652):     x20  0000007f746c9048  x21  0000007f81ed4990  x22  0000007f6c80e0c0  x23  0000000070b89838`
`01-28 20:19:10.727 I/DEBUG   (  652):     x24  0000007f82da1be0  x25  0000007f81ed4990  x26  0000007f82d8edf8  x27  0000007f82da61e8`
`01-28 20:19:10.727 I/DEBUG   (  652):     x28  0000007f82d7a000  x29  0000007f81ed46f0  x30  0000007f82ce211c`
`01-28 20:19:10.727 I/DEBUG   (  652):     sp   0000007f81ed46f0  pc   0000007f82ce1fdc  pstate 0000000060000000`
`01-28 20:19:10.727 I/DEBUG   (  652): backtrace:`
`01-28 20:19:10.727 I/DEBUG   (  652):     #00 pc 000000000032afdc  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+300)`
[...]
`01-28 20:19:10.770 F/libc    ( 1734): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1c in tid 1748 (Signal Catcher)`
`01-28 20:19:14.196 I/nativedumper( 5679): Process pid 32331(org.kustom.wallpaper.service org.kustom.wallpaper.service) died by signal - Catcher.`
`01-28 20:19:14.221 D/nativedumper( 5679): Tombstone path:/data/tombstones/tombstone_06 UUID:eabbd4ab-23aa-4ddc-a979-353753a50ed9 PID:32331`
`01-28 20:19:14.295 I/DEBUG   (  652): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c`
`01-28 20:19:14.353 I/DEBUG   (  652): backtrace:`
`01-28 20:19:14.353 I/DEBUG   (  652):     #00 pc 000000000032afdc  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+300)`
`01-28 20:19:14.353 I/DEBUG   (  652):     #01 pc 00000000002fe040  /system/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+260)`
`01-28 20:19:14.353 I/DEBUG   (  652):     #02 pc 0000000000309104  /system/lib64/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+172)`
`01-28 20:19:14.353 I/DEBUG   (  652):     #03 pc 00000000002ea258  /system/lib64/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+96)`
`01-28 20:19:14.353 I/DEBUG   (  652):     #04 pc 00000000002f2adc  /system/lib64/libart.so (art::SignalCatcher::HandleSigQuit()+1104)`
`01-28 20:19:14.353 I/DEBUG   (  652):     #05 pc 00000000002f36f0  /system/lib64/libart.so (art::SignalCatcher::Run(void*)+456)`
`01-28 20:19:14.353 I/DEBUG   (  652):     #06 pc 000000000001ba00  /system/lib64/libc.so (__pthread_start(void*)+52)`
`01-28 20:19:14.353 I/DEBUG   (  652):     #07 pc 0000000000017cf0  /system/lib64/libc.so (__start_thread+16)`
`01-28 20:19:14.446 I/DEBUG   (  652): Tombstone written to: /data/tombstones/vendor/minitombstone_06`

KLWP is a live wallpaper app.

The (imo) relevant line from tombstone_06 (the KLWP-related crash):
`pid: 32331, tid: 32344, name: Signal Catcher  >>> org.kustom.wallpaper.service <<<`

The one from minitombstone_06:
`pid: 1734, tid: 1748, name: Signal Catcher  >>> system_server <<<`

I hope these are indeed Xposed-related. At least the one I reported about earlier is.

Here's the new files: https://drive.google.com/folderview?id=0B3--EMNkM4LadHJnTDJYRE4yOXc&usp=sharing

@rovo89, is this in the right place btw? I followed your XDA link, but afterwards saw other different places on your GitHub, including 'Xposed'.

**Comment by rovo89** [comment]
Sorry, seems like I always skipped over this issue. Does it still occur with the latest Xposed version?

**Comment by jelbo** [comment]
Hi rovo89, no it's not an issue anymore. Me and several other Z4 Tablet owners have been running Xposed fine for some time now.

I can't exactly remember what fixed this, but it could have been the Marhsmallow firmware upgrade we got, the new Xposed builds or fixes in the mandatory custom kernel we're running (AndroPlusKernel).

Thanks for checking back on this anyway :)

**Comment by rovo89** [comment]
OK, I'll close the issue then.
