### ISSUE TITLE
Wiko Pulp 3G reboots itself every 5-10 mins 

### ISSUE THREAD

**Issue by kuromobibkk** [rovo89/android_art#29]
I've installed xposedv.79 sdk_arm22.zip in my Wiko Pulp 3G, stock rom updated version, SuperSU rooted, first I've install its all perfect no sign of error. Then its took a couple days before its start reboot itself every 5-10 mins.
Even though I've flashed an uninstaller.zip, it still reboot itself. I have to flash rom to stop it.
I've tried for a couple times to make sure that Xposed may cause this.
I used only 2 modules Flat Stlye Bar and Greenify.
Please help me, Thank you.

**Comment by rovo89** [comment]
> Even though I've flashed an uninstaller.zip, it still reboot itself.

Then it can hardly be caused by Xposed because Xposed isn't active after flashing the uninstaller.

If you really believe that it's caused by Xposed, please try again with the latest Xposed version and without any modules. Immediately after the reboot occurs, please take a logcat.
