### ISSUE TITLE
A purposal for open-source ART ROMs

### ISSUE THREAD

**Issue by arter97** [rovo89/android_art#3]
Current Xposed Installer replaces the existing ART binaries, which may be the only way to work with prebuilt manufacturer's ROMs, but it can be better with already open-source'ed ROMs out there.

Can I ask to implement kind of a "Xposed ART binaries indication" thing to dynamically pass ART binaries installation when the ROM is already built, ready for Xposed?
Code may be like this :
if strings /system/lib/libart-compiler.so | grep -q xposed ; then
skip_art_installation
fi

We can make use of what's already committed(mostly performance and stability improvements) on android_art in the existing ROMs that way.

Thanks :)

**Comment by rovo89** [comment]
I'm not sure whether we can see the ART libraries/binaries as independent piece of software. They are somehow bound to app_process and XposedBridge.jar as well. So updating just one of these will lead to untested situations and will possibly crash the system.

So **if** a ROM decides to bundle Xposed, it should probably include all parts of it and ask users not to update (as that would overwrite the ART files). The detection whether Xposed is installed properly could be improved a bit, so users don't think that the installation still has to be done.

**Comment by arter97** [comment]
Hmm, never thought of that, but I still think using a prebuilt ART binaries
from other AOSP tree when it can be built from the same Android tree is not
the best idea.

What I've thought of originally was, just bundling Xposed-ready ART
binaries from the build time and let the users to choose to install the
rest of the Xposed component(app_process, XposedBridge.jar etc) to make
Xposed fully functional.
I pictured that your ART modifications won't work(thus cause no extra
troubles) unless it's bonded with the rest of the Xposed component.

Can you come up with an idea of source-buildable Xposed integration(perhaps
just the ART part) or maybe a totally better solution?

**Comment by rovo89** [comment]
As I said - ROMs that want to bundle Xposed should include all components. Or people could offer a customized ZIP for that, with their source-built ART libraries and my other files. You're right that my ART files shouldn't create too much overhead if Xposed is not enabled. But skipping the installation of the ART files seems to create too many unplanned situations (i.e. app_process might need an older/newer version of the ART files to work correctly) that I'm not willing to support.
