### ISSUE TITLE
Reboot issue 

### ISSUE THREAD

**Issue by pikachukaki** [rovo89/android_art#32]
This is what im seeing when I press reboot from inside the installer busybox is installed every module works properly... 
![screenshot_2016-04-03-17-10-59](https://cloud.githubusercontent.com/assets/3009586/14232830/4c355ef2-f9bf-11e5-9cc3-4fbcc8fe3fe0.png)

**Comment by rovo89** [comment]
Duplicate of https://github.com/rovo89/XposedInstaller/issues/309
