### ISSUE TITLE
[CM13][titan] Bootloop on installation

### ISSUE THREAD

**Issue by ToasterDEV** [rovo89/android_art#45]
Device: Motorola Moto G 2014 (titan) (XT1064)
ROM: Cyanogenmod 13
Xposed version: v85_arm
Detailed description of the issue (including exact error messages if applicable):
The Xposed Installer I use is the latest one by dvdandroid. This has happened before, and it has been fixed through a factory reset. There doesn´t seem to be a specific cause, however it happens at random and lately always when I try to install the framework through TWRP 3.0.0-0.
Things you have already tried to resolve it:
Factory Reset (Temporary solution)
Xposed Uninstaller Zip
Steps to reproduce:
Flash Xposed through Recovery.
Logs:
http://pastebin.com/tr3CpSDD
Module List:
http://pastebin.com/SsQ21BCv

**Comment by rovo89** [comment]
There are a lot of errors in the log. My suggestion is to try and delete `/data/data/de.robv.android.xposed.installer/conf/modules.list` the next time when this happens. That way, you disable all modules. If it boots then, it's a module issue. I suspect it might be `com.bubblesoft.android.bubbleupnp`, as that one is trying to call `Environment.getExternalStorageDirectory()`, which in the background tries to call a service that isn't available. You can also try to disable just this one module.

BubbleUPnPXMod

**Comment by ToasterDEV** [comment]
Thanks. Uninstalling BubbleUPNP worked. Yet, it seems a little bit weird since I had it enabled for several days before it started going berserk. Is it common behavior for apps to randomly malfunction?

**Comment by rovo89** [comment]
Maybe you simply didn't have the module enabled, the app itself should be fine. Or you changed some settings. Anyway, good to know that it's fixed.
