### ISSUE TITLE
Support for new kryo optimizations (32 bit) 

### ISSUE THREAD

**Issue by TheCrazyLex** [rovo89/android_art#49]
Please merge this to support the new kryo optimizations: https://github.com/AOSPA/android_art/commit/580979474ad3c49c72a8f5ea0bbba55586310872

Reasons for merge are basically the same outlined here: https://github.com/rovo89/android_art/pull/44

Preferrably this would be merged in marshmallow and nougat too. 

Thank you in advance!

**Comment by TheCrazyLex** [comment]
Additionally this would be good: https://github.com/AOSPA/android_art/commit/88d739344fa09808ef0d2d99f54f39261a954016

**Comment by TheCrazyLex** [comment]
Merged in AOSP

**Comment by robobarney** [comment]
Thanks for the first time in the UK.
