### ISSUE TITLE
Double logs after fresh boot

### ISSUE THREAD

**Issue by LineOne11** [rovo89/android_art#54]
Hi. Firstly thanks for all the great work!!
I have an issue.
This has been happening all along but only now i am reporting this due to finally aquiring an official build.

After a fresh boot. ( Even after clearing logs before shutting down )
There is always double logs.
This happens with or without any modules installed.
On the old (unofficial) build i was using i seen times when my own module would somehow make the log write only once on boot. But i have no clue as to why my module did this as i had no methods being hooked in the system or xposed. Only hooking a method from a game.
Anyway at the moment ive only got one module from "lucky patcher". Heres my log ( or logs ) this is from a single log file after a single boot.
10-30 15:27:17.450 I/Xposed  ( 3140): -----------------
10-30 15:27:17.450 I/Xposed  ( 3140): Starting Xposed version 86, compiled for SDK 23
10-30 15:27:17.450 I/Xposed  ( 3140): Device: SM-G928I (samsung), Android version 6.0.1 (SDK 23)
10-30 15:27:17.450 I/Xposed  ( 3140): ROM: MMB29K.G928IDVU2BPG3
10-30 15:27:17.450 I/Xposed  ( 3140): Build fingerprint: samsung/zenltedv/zenlte:6.0.1/MMB29K/G928IDVU2BPG3:user/release-keys
10-30 15:27:17.450 I/Xposed  ( 3140): Platform: arm64-v8a, 64-bit binary, system server: yes
10-30 15:27:17.450 I/Xposed  ( 3140): SELinux enabled: yes, enforcing: yes
10-30 15:27:17.490 I/Xposed  ( 3140): -----------------
10-30 15:27:17.490 I/Xposed  ( 3140): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-30 15:27:17.780 I/Xposed  ( 3140): Detected ART runtime
10-30 15:27:17.800 I/Xposed  ( 3140): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-30 15:27:18.400 I/Xposed  ( 3140): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LOCK-1/base.apk
10-30 15:27:18.530 I/Xposed  ( 3140):   Loading class com.chelpus.XSupport
10-30 15:27:28.060 I/Xposed  ( 3141): -----------------
10-30 15:27:28.060 I/Xposed  ( 3141): Starting Xposed version 86, compiled for SDK 23
10-30 15:27:28.060 I/Xposed  ( 3141): Device: SM-G928I (samsung), Android version 6.0.1 (SDK 23)
10-30 15:27:28.060 I/Xposed  ( 3141): ROM: MMB29K.G928IDVU2BPG3
10-30 15:27:28.060 I/Xposed  ( 3141): Build fingerprint: samsung/zenltedv/zenlte:6.0.1/MMB29K/G928IDVU2BPG3:user/release-keys
10-30 15:27:28.060 I/Xposed  ( 3141): Platform: arm64-v8a, 32-bit binary, system server: no
10-30 15:27:28.060 I/Xposed  ( 3141): SELinux enabled: yes, enforcing: yes
10-30 15:27:28.070 I/Xposed  ( 3141): -----------------
10-30 15:27:28.070 I/Xposed  ( 3141): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-30 15:27:28.280 I/Xposed  ( 3141): Detected ART runtime
10-30 15:27:28.300 I/Xposed  ( 3141): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-30 15:27:28.590 I/Xposed  ( 3141): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LOCK-1/base.apk
10-30 15:27:28.690 I/Xposed  ( 3141):   Loading class com.chelpus.XSupport

**Comment by rovo89** [comment]
Look closer. One "start" is for the 64-bit binary, the other one for the 32-bit library. On a 64-bit device/ROM, two Java stacks are started, especially for those apps which come with native libraries that are only compiled for 32-bit. Xposed obviously needs to be initialized for both of these stacks/processes.

**Comment by wanam** [comment]
This is a normal behaviour on 64bit devices, the first one is logging zygote 64 bit start, the second one zygote 32bit.

**Comment by rovo89** [comment]
After answering, I was wondering if I should split up the logs... but I think it would be rather counter-productive. Apart from the apparent duplication during the start, it's actually good that we see logs from both stacks in a single place.

**Comment by fda77** [comment]
Warez useres should not be supported. As he has money to buy a Samsung S6 (~650€), there is no need to steal apps for some bucks

**Comment by LineOne11** [comment]
@fda77 Im actually developing a game, (based around hacking) one would expect to see "hacker's" in this game.
As of this. I need to verify my own code. And hook my own methods. In an attempt to look at my code from an end-user's perspective (i also decompile my apk and read my own source before release). it doesnt concern my phone or even how i got my phone (paid or not). I couldve stolen it for all you know.  I agree about the "wares should not be supported", though i dont agree that "you" have the right to pick warez users from developers. @rovo89 thanks for such a speedy reply. Sorry for double posting i thought the first(this) didnt upload/send. Thanks again for all your hard work. Some of the new tweaks ive made since first learning about xposed makes my life soo much easier

**Comment by LineOne11** [comment]
@wanam also thanks for your reply. And your unofficial build, it was actually your build i was using... and am using again..

**Comment by fda77** [comment]
@LineOne11: As a developer you should not be interested to fix bugs in warez. Especially if it's used to hack your app

**Comment by LineOne11** [comment]
@fda77 actually i think xposed is amazing. If i could id donate.. and why would i want to fix the bugs? Because im running it on MY "Samsung S6 (~650€)".  And like i said before im using it to hack my app. Thats why other arent.
Not really the place for you to come in and try to start an argument in someones project but eh.. i guess its up to the parents to keep the children off the net. How about you have some respect and read it as someone requested support for someone elses work and it had nothing to do with you.

**Comment by fda77** [comment]
@LineOne11: The warez you promote here is banned on XDA. So if you need it, ask on appropriate sites where you got it
