### ISSUE TITLE
Xposed causing Bootloop [Nexus 7(Deb) : CM 13.1]

### ISSUE THREAD

**Issue by digital-idiot** [rovo89/android_art#56]
Xposed Framework : v86 SDK 23
Xposed Installer : v3.1.1
TWRP : v3.0.2-0
CM Build : 13-NOV-2016

Flashed xposed framework without any error. Device boots fine if there is no xposed module or no module is currently activated. If there is module(s) already active in the app, it causes bootloop. Same thing happens if rebooted after activating any module(s).
Logs:
1. Logcat after flashing Xposed Framework (No module is active) : [logcat - pastebin](http://pastebin.com/PAFSze28)
2. Logcat during bootloop(Modules Activated) : [logcat_bootloop - pastebin](http://pastebin.com/qNhUw35k)
3. Xposed's own Log : [Xposed Log - pastebin](http://pastebin.com/AHks4jpU)

Tested using the module Youtube Adaway. Result does not change for other modules.
N.B.: Everything worked just fine till the CM 13.1 build 08-NOV-2016. Might be a CM bug also, not sure.

**Comment by rovo89** [comment]
Does this still occur with v89?

**Comment by digital-idiot** [comment]
No the issue is fixed. Forgot to close the issue
