### ISSUE TITLE
 error: undefined reference to 'art::mirror::Object::Clone(art::Thread*, unsigned int)'

### ISSUE THREAD

**Issue by liumengdeqq** [rovo89/android_art#59]
frameworks/base/cmds/xposed/libxposed_art.cpp:144: error: undefined reference to 'art::mirror::ArtMethod::EnableXposedHook(art::ScopedObjectAccess&, _jobject*)'
   frameworks/base/cmds/xposed/libxposed_art.cpp:189: error: undefined reference to 'art::mirror::Object::Clone(art::Thread*, unsigned int)'
   frameworks/base/cmds/xposed/libxposed_art.cpp:189: error: undefined reference to 'art::mirror::Object::Clone(art::Thread*, unsigned int)'
   frameworks/base/cmds/xposed/libxposed_art.cpp:189: error: undefined reference to 'art::mirror::Object::Clone(art::Thread*, unsigned int)'
   frameworks/base/cmds/xposed/libxposed_art.cpp:85: error: undefined reference to 'art::mirror::ArtMethod::xposed_callback_class'
   collect2: error: ld returned 1 exit status
   make: *** [out/target/product/s900_96board/obj/SHARED_LIBRARIES/libxposed_art_intermediates/LINKED/libxposed_art.so] 错误 1
   
   #### make failed to build some targets (01:13 (mm:ss)) ####

**Comment by rovo89** [comment]
https://github.com/rovo89/Xposed/issues/217
