### ISSUE TITLE
* [out/target/product/s900_96board/obj/SHARED_LIBRARIES/libxposed_art_intermediates/libxposed_art.o]

### ISSUE THREAD

**Issue by liumengdeqq** [rovo89/android_art#60]
frameworks/base/cmds/xposed/libxposed_art.cpp:123:56: error: no matching function for call to 'art::mirror::ArtMethod::EnableXposedHook(JNIEnv*&, _jobject*&)'
     artMethod->EnableXposedHook(env, javaAdditionalInfo);
                                                        ^

**Comment by rovo89** [comment]
Stop spamming the issue tracker with "issues" that you cause yourself. You didn't mention anything about what you did and what you're trying to do, but most likely, you are trying to compiled an old version of the Xposed project (before v74 with https://github.com/rovo89/Xposed/commit/6a8c2db5523377742a2c40fbd317b559e46b386f) against the latest ART tree. Just follow the instructions and all should be fine.
