### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by duoniduoni** [rovo89/android_art#63]
I get a problem here :

@rovo89 help me please !

HeapTaskDaemon  >>> system_server <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
    x0   0000007fa532b2d8  x1   00000000705e2e08  x2   0000000000000000  x3   0000000000000000
    x4   0000000000000000  x5   0000000000000000  x6   0000000072fdf760  x7   0000000000000000
    x8   0000000000000000  x9   0000000000000000  x10  0000000010000000  x11  ffffffffffffffff
    x12  0000007fa532b5f0  x13  0000000000000011  x14  0000007fa666cd20  x15  003b9aca00000000
    x16  0000007fa62287d0  x17  0000007fa864b240  x18  0000000000000000  x19  0000007fa532b5c8
    x20  0000000070b975a0  x21  00000000705e2e08  x22  0b0cfb07bedf50e4  x23  0000007ffe363710
    x24  0000007ffe362af0  x25  0000007fa621b9e0  x26  0000007fa532b5c8  x27  0000000000000000
    x28  0b0cfb07bedf50e4  x29  0000007fa532b350  x30  0000007fa6066f90
    sp   0000007fa532b290  pc   0000007fa6066ffc  pstate 0000000020000000

backtrace:
    #00 pc 000000000045dffc  /system/lib64/libart.so (_ZN3art19ReferenceMapVisitorINS_19RootCallbackVisitorEE15VisitQuickFrameEv+256)
    #01 pc 000000000045deec  /system/lib64/libart.so (_ZN3art19ReferenceMapVisitorINS_19RootCallbackVisitorEE10VisitFrameEv+24)
    #02 pc 0000000000444e14  /system/lib64/libart.so (_ZN3art12StackVisitor9WalkStackEb+668)
    #03 pc 0000000000459c44  /system/lib64/libart.so (_ZN3art6Thread10VisitRootsEPNS_11RootVisitorE+1028)
    #04 pc 000000000046751c  /system/lib64/libart.so (_ZNK3art10ThreadList10VisitRootsEPNS_11RootVisitorE+104)
    #05 pc 000000000043c4c8  /system/lib64/libart.so (_ZN3art7Runtime10VisitRootsEPNS_11RootVisitorENS_14VisitRootFlagsE+32)
    #06 pc 00000000001ea0e0  /system/lib64/libart.so (_ZN3art2gc9collector9MarkSweep10PausePhaseEv+160)
    #07 pc 00000000001e9e6c  /system/lib64/libart.so (_ZN3art2gc9collector9MarkSweep9RunPhasesEv+288)
    #08 pc 00000000001e2420  /system/lib64/libart.so (_ZN3art2gc9collector16GarbageCollector3RunENS0_7GcCauseEb+332)
    #09 pc 0000000000212518  /system/lib64/libart.so (_ZN3art2gc4Heap22CollectGarbageInternalENS0_9collector6GcTypeENS0_7GcCauseEb+3048)
    #10 pc 0000000000219ae4  /system/lib64/libart.so (_ZN3art2gc4Heap12ConcurrentGCEPNS_6ThreadEb+124)
    #11 pc 0000000000220dc0  /system/lib64/libart.so (_ZN3art2gc4Heap16ConcurrentGCTask3RunEPNS_6ThreadE+36)
    #12 pc 0000000000242b5c  /system/lib64/libart.so (_ZN3art2gc13TaskProcessor11RunAllTasksEPNS_6ThreadE+64)
    #13 pc 000000007416f5b0  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x2a81000)

**Comment by duoniduoni** [comment]
this is Android 7 ~

**Comment by rovo89** [comment]
There is no Xposed for Android 7 yet.
