### ISSUE TITLE
Xposed 88.1 ARM64 bootlooping on LG G6

### ISSUE THREAD

**Issue by test32443** [rovo89/android_art#65]
Device: LG G6 US997 (US Unlocked model)
ROM: (Stock Android 7.0, Security Patch level: September 1,2017; Kernel version: 3.18.31; Build Number: NRD90U; Software Version: US99715a; Security Software Version: MDF v3.0 Release 1) + Magisk 14.0
Xposed version: xposed-v88.1-sdk24-arm64.zip
Detailed description of the issue: After installing Xposed from recovery, device goes to bootloop.
Things you have already tried to resolve it: Tried Magisk version of xposed v88.1 with same result

Logcat log: https://pastebin.com/ZgKxjSQ5

**Comment by rovo89** [comment]
How long did you wait? The log spans ~3 minutes. app_process32 seems to be ready, but app_process64 seems to be still waiting until some additional data has been compiled for the .odex files. This isn't done yet for GmsCore.odex by the time when the log ends. So chances are you just need to wait a bit longer.

**Comment by test32443** [comment]
It is possible that logs are not complete, but I've seen 3 reboots in a row - LG plays a sound every time it boots, so it is not that I am not waiting long enough. Would you like me to collect more logs?

**Comment by test32443** [comment]
Ok, apparently it took 5 reboots after which system booted properly. I am closing this issue now.
