### ISSUE TITLE
dexoat Fails to build boot.art image(Samsung 7.1.1)

### ISSUE THREAD

**Issue by me2151** [rovo89/android_art#67]
Hello. I am attempting to use Xposed 88.1 on the Galaxy Note8(7.1.1 API 25 arm64) and I'm encountering a bootloop issue. Ive narrowed it down to the art files and managed to get some information using adb bugreport as I cannot get a logcat from the boot(adb offline).

Essentially this is where my boot fails:

10-19 20:40:04.680 19545 19545 I art     : GenerateImage: /system/bin/dex2oat --image=/data/dalvik-cache/arm64/system@framework@boot.art --dex-file=/system/framework/SmpsManager.jar --dex-file=/system/framework/core-oj.jar --dex-file=/system/framework/core-libart.jar --dex-file=/system/framework/conscrypt.jar --dex-file=/system/framework/okhttp.jar --dex-file=/system/framework/core-junit.jar --dex-file=/system/framework/bouncycastle.jar --dex-file=/system/framework/ext.jar --dex-file=/system/framework/fram10-19 20:40:14.804 19545 19545 E art     : Could not create image space with image file '/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Failed to generate image '/data/dalvik-cache/arm64/system@framework@boot.art': Failed execv(/system/bin/dex2oat --image=/data/dalvik-cache/arm64/system@framework@boot.art --dex-file=/system/framework/SmpsManager.jar --dex-file=/system/framework/core-oj.jar --dex-file=/system/framework/core-libart.jar --dex-file=/system/framework/consc10-19 20:40:14.804 19545 19545 E art     : Attempted image: /system/framework/boot.art
10-19 20:40:15.600 19545 19545 W art     : Skipping non-existent dex file '/system/framework/oem-services.jar'

That sadly was the most i saw error wise. It is impossible to get a logcat of the bootloop unfortunatly. But I removed the libart.so and the dexoat files from the zip for the framework and it BOOTS but obviously xposed installer says it isnt running

EDIT: Here is the full bugreport https://gist.github.com/me2151/00228bda14790fe0915b52e02af37567

**Comment by rovo89** [comment]
https://github.com/rovo89/Xposed/issues/273

**Comment by me2151** [comment]
Yes But not resolved. Currently trying to create a binary to save a logcat locally on the device

**Comment by rovo89** [comment]
One issue is enough.

**Comment by me2151** [comment]
You closed my other one. So i reopened this one.

**Comment by rovo89** [comment]
No, the other one is not closed.

**Comment by me2151** [comment]
I see that now. I apologize. Thank you.
