### ISSUE TITLE
Crash at early boot - Moto Z (XT1650-03 - griffin)

### ISSUE THREAD

**Issue by ghost** [rovo89/android_art#68]
Hello,

My config :
- Moto Z (XT1650-03 - griffin) with stock 7.0 (retus)
- Bootloader unlocked
- Rooted : superuser-r259
- Recovery : TWRP-3.1.1-0
- SD card formatted as adopted storage (I don't know if it's useful info)

The problem : After flashing xposed-***.zip, system won't boot at all, the phone is stuck at the orange boot screen (that happens at each boot anyway, after you unlocked the bootloader). See below for an example of the orange screen.

Versions of Xposed used :
- xposed-v88-sdk24-arm64.zip
- xposed-v88.1-sdk24-arm64.zip

Procedure to reproduce :
- Boot recovery (TWRP)
- Install on of the zips above, eg by adb sideload - installs without error
- Reboot system
- The usual orange warning screen appears, the phone vibrates after 5 secondes (as usual)...and then it gets stuck here

I would be happy to include logs, as stated in your XDA post, however it's totally impossible so early in boot - I tried.

Illustration of the orange boot screen :
![example](https://user-images.githubusercontent.com/16407415/31975119-66cfc2da-b92f-11e7-85cd-1b3f86b75bcc.png)

**Comment by rovo89** [comment]
That sounds like modifying the /system partition is the reason here, not Xposed itself. Some tools like SuperSU disable "dm-verity" and therefore allow the system to be modified. Alternatively, you could try an unofficial systemless variant of Xposed.

**Comment by ghost** [comment]
Thanks for your answer. It was because of dm-verity. Reflashed stock and rooted with Magisk, it works just fine now.
