### ISSUE TITLE
Freezing related to ART

### ISSUE THREAD

**Issue by KaMyKaSii** [rovo89/android_art#69]
Official Xposed v88.1, Android 7.1.1 AOSP on Quantum Go 4G.
My device has already frozen twice for about 25 seconds and I could find the following Xposed logs:

[xposed_error_20171025_075448.log](https://github.com/rovo89/android_art/files/1414846/xposed_error_20171025_075448.log)
[xposed_error_20171025_114834.log](https://github.com/rovo89/android_art/files/1414847/xposed_error_20171025_114834.log)

**Comment by rovo89** [comment]
Same as this: https://github.com/rovo89/Xposed/issues/247
