### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhangtengchao** [rovo89/android_art#70]
1-29 20:14:16.584 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/am.odex: Invalid oat header for '/system/framework/oat/arm64/am.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.584 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/android.test.runner.odex: Invalid oat header for '/system/framework/oat/arm64/android.test.runner.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.585 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/appwidget.odex: Invalid oat header for '/system/framework/oat/arm64/appwidget.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.585 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/bmgr.odex: Invalid oat header for '/system/framework/oat/arm64/bmgr.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.585 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/bu.odex: Invalid oat header for '/system/framework/oat/arm64/bu.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.586 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/com.android.future.usb.accessory.odex: Invalid oat header for '/system/framework/oat/arm64/com.android.future.usb.accessory.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.586 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/com.android.location.provider.odex: Invalid oat header for '/system/framework/oat/arm64/com.android.location.provider.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.586 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/com.android.media.remotedisplay.odex: Invalid oat header for '/system/framework/oat/arm64/com.android.media.remotedisplay.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.587 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/com.android.mediadrm.signer.odex: Invalid oat header for '/system/framework/oat/arm64/com.android.mediadrm.signer.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.587 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/content.odex: Invalid oat header for '/system/framework/oat/arm64/content.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.587 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/dpm.odex: Invalid oat header for '/system/framework/oat/arm64/dpm.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.587 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/ethernet-service.odex: Invalid oat header for '/system/framework/oat/arm64/ethernet-service.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.588 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/hid.odex: Invalid oat header for '/system/framework/oat/arm64/hid.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.588 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/ime.odex: Invalid oat header for '/system/framework/oat/arm64/ime.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.588 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/input.odex: Invalid oat header for '/system/framework/oat/arm64/input.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.588 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/javax.obex.odex: Invalid oat header for '/system/framework/oat/arm64/javax.obex.odex': Invalid oat version, expected 0x3037390, got 0x3038380.
01-29 20:14:16.589 1125-1125/? E/Xposed: Failed to open oat /system/framework/oat/arm64/media_cmd.odex: Invalid oat header for '/system/framework/oat/arm64/media_cmd.odex': Invalid oat version, expected 0x3037390, got 0x3038380.

Device：Nexus6P，arm64，AOSP on angler，7.1.1

**Comment by rovo89** [comment]
Is that really AOSP? Or some modified ROM? Because the oat version shouldn't be changed...

**Comment by zhangtengchao** [comment]
sorry,I use wrong art source.
