### ISSUE TITLE
Fatal signal 11 (SIGSEGV) on libc

### ISSUE THREAD

**Issue by wanam** [rovo89/android_art#9]
Hi @rovo89 ,

I'm trying to get xposed support for TW arm64 Roms, so i used this repo + the 3 workaround commits on @arter97 repo to get it working on deodexed TW roms.

I made some changes to the core-libart.jar to make it compatible with aosp one, according to the logs, xposed seems to load:
05-28 11:52:25.740  2978  2978 D XposedStartupMarker: Current time: 1432810345, PID: 2978
05-28 11:52:25.740  2978  2978 I Xposed  : -----------------
05-28 11:52:25.740  2978  2978 I Xposed  : Starting Xposed binary version 61, compiled for SDK 21
05-28 11:52:25.740  2978  2978 I Xposed  : Device: SM-G920F (samsung), Android version 5.0.2 (SDK 21)
05-28 11:52:25.740  2978  2978 I Xposed  : ROM: WanamLite-1.3-LRX22G.G920FXXU1AOE4
05-28 11:52:25.740  2978  2978 I Xposed  : Build fingerprint: samsung/zerofltexx/zeroflte:5.0.2/LRX22G/G920FXXU1AOE4:user/release-keys
05-28 11:52:25.740  2978  2978 I Xposed  : Platform: arm64-v8a, 64-bit binary, system server: yes
05-28 11:52:25.740  2978  2978 I Xposed  : SELinux enabled: yes, enforcing: yes
05-28 11:52:25.740  2978  2978 I Xposed  : -----------------
05-28 11:52:25.740  2978  2978 I Xposed  : Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-28 11:52:25.750  2978  2978 D AndroidRuntime: 
05-28 11:52:25.750  2978  2978 D AndroidRuntime: >>>>>> AndroidRuntime START de.robv.android.xposed.XposedBridge <<<<<<

But i'm still getting a bootloop with bellow issue (complete logs here: https://www.dropbox.com/s/bz9qlxdgekkzjpk/dumpstate_app_native.txt.gz?dl=0) :

05-28 11:53:04.280  4803  4803 D ICD     : file: system/bin/dalvikvm
05-28 11:53:04.280  4803  4803 D ICD     : chec: 7af6665fcce6ee8a55bb201f565a7b6af34291493117207317d741b07d7a34c7
05-28 11:53:04.280  4803  4803 D ICD     : cafn: system/bin/dalvikvm
05-28 11:53:04.290  4803  4803 D ICD     : 2hex: ad6bbb1856e6292f0580244bf87c225df318c1e93ec67ae36c6ec21818c639b1
05-28 11:53:04.290  4803  4803 E ICD     : idx: 7
05-28 11:53:04.290  4803  4803 D ICD     : rslt: FAIL
05-28 11:53:04.290  4803  4803 D ICD     : Result of Groups : TZ_DRM(0), FIDD(0), CC(8) ret(8)
05-28 11:53:04.290  4803  4803 D ICD     : write in file icdr
05-28 11:53:04.290  4803  4803 D ICD     : Set oemflag [CC]: 00
05-28 11:53:04.290  4803  4803 D ICD     : icd (8)
05-28 11:53:04.290  4803  4803 D ICD     : SysScope packages are exist.
05-28 11:53:04.320  4798  5115 W Zygote  : Class not found for preloading: android.util.secutil.LogSwticher
05-28 11:53:04.320  4798  4798 W Zygote  : Class not found for preloading: com.android.okhttp.ConfigAwareConnectionPool$1
05-28 11:53:04.320  4798  5115 I Zygote  : !@prldclss2: 520 classes in 110ms.
05-28 11:53:04.350  4798  5114 I art     : Thread[9,tid=5114,WaitingForJniOnLoad,Thread_=0x7f77db1800,peer=0x12de15e0,"prct_1"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
05-28 11:53:04.350  4798  5114 D MtpDeviceJNI: register_android_mtp_MtpDevice
05-28 11:53:04.350  4798  5114 I art     : Thread[9,tid=5114,WaitingForJniOnLoad,Thread_=0x7f77db1800,peer=0x12de15e0,"prct_1"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
05-28 11:53:04.350  4798  5114 I art     : Thread[9,tid=5114,WaitingForJniOnLoad,Thread_=0x7f77db1800,peer=0x12de15e0,"prct_1"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
05-28 11:53:04.360  4798  5111 W Resources: Preloaded drawable resource #0x108081b (android:drawable/text_cursor_holo_light) that varies with configuration!!
05-28 11:53:04.360  4798  5111 W Resources: Preloaded drawable resource #0x108081a (android:drawable/text_cursor_holo_dark) that varies with configuration!!
05-28 11:53:04.370  4798  5114 I Zygote  : !@prldclss1: 905 classes in 155ms.
05-28 11:53:04.370  4798  4798 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdad00000000217 in tid 4798 (main)
05-28 11:53:04.420  2946  2946 I DEBUG   : *_\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
05-28 11:53:04.420  2946  2946 I DEBUG   : Build fingerprint: 'samsung/zerofltexx/zeroflte:5.0.2/LRX22G/G920FXXU1AOE4:user/release-keys'
05-28 11:53:04.420  2946  2946 I DEBUG   : Revision: '11'
05-28 11:53:04.420  2946  2946 I DEBUG   : ABI: 'arm64'
05-28 11:53:04.420  2946  2946 I DEBUG   : pid: 4798, tid: 4798, name: main  >>> zygote64 <<<
05-28 11:53:04.420  2946  2946 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdad00000000217
05-28 11:53:04.430  2946  2946 I DEBUG   :     x0   0000007f77d973c0  x1   0000007fd1dfa100  x2   0000000000000001  x3   000000006f6d6de0
05-28 11:53:04.430  2946  2946 I DEBUG   :     x4   0000000000000000  x5   0000007f77d1d75c  x6   0000000000000000  x7   0000007f77d1d758
05-28 11:53:04.430  2946  2946 I DEBUG   :     x8   0000000000000000  x9   0000000000430000  x10  0000000000000000  x11  0000000000000000
05-28 11:53:04.430  2946  2946 I DEBUG   :     x12  0000000000000000  x13  0000000000430000  x14  0000000000550000  x15  0000000000430000
05-28 11:53:04.430  2946  2946 I DEBUG   :     x16  0000000000000000  x17  77dad0000000007f  x18  0000007f77cfd470  x19  00000000000003e8
05-28 11:53:04.430  2946  2946 I DEBUG   :     x20  0000000072e5a020  x21  0000007f77dad000  x22  0000007f77dad090  x23  0000007fd1dfa300
05-28 11:53:04.430  2946  2946 I DEBUG   :     x24  0000000070644060  x25  0000007fd1dfa348  x26  0000007fd1dfa310  x27  0000000000000001
05-28 11:53:04.430  2946  2946 I DEBUG   :     x28  0000000070657d1a  x29  0000007fd1dfa1b0  x30  0000000072e83968
05-28 11:53:04.430  2946  2946 I DEBUG   :     sp   0000007fd1dfa0f0  pc   0000000072e5a024  pstate 0000000060000000
05-28 11:53:04.430  2946  2946 I DEBUG   : 
05-28 11:53:04.430  2946  2946 I DEBUG   : backtrace:
05-28 11:53:04.430  2946  2946 I DEBUG   :     #00 pc 0000000000000024  /data/dalvik-cache/arm64/system@framework@boot.oat

**Comment by rovo89** [comment]
I'm afraid I can't help you here. There are too many unknown variables and changes done by you. The only thing I noticed is that the crash seems to happen in the compiled .oat file, so the error might be somewhere in the compiler logic. That's a very wide and complicated topic though, and the uncertainty about Samsung's changes make it even harder.
